version: '3.8'

services:
  termogroup:
    container_name: termogroup
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    restart: always